CREATE TABLE `invoiceItems` (
	`id` int AUTO_INCREMENT NOT NULL,
	`invoiceId` int NOT NULL,
	`description` varchar(512) NOT NULL,
	`frequency` varchar(64) DEFAULT 'Once Off',
	`vat` varchar(32) DEFAULT 'No VAT',
	`unitPrice` decimal(12,2) NOT NULL,
	`quantity` int DEFAULT 1,
	`lineTotal` decimal(12,2) NOT NULL,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `invoiceItems_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `invoices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`invoiceNumber` varchar(32) NOT NULL,
	`clientName` varchar(255) NOT NULL,
	`clientContact` varchar(255),
	`clientPhone` varchar(64),
	`clientEmail` varchar(320),
	`projectName` varchar(255),
	`projectSummary` text,
	`status` enum('draft','sent','paid','overdue') NOT NULL DEFAULT 'sent',
	`subtotal` decimal(12,2) NOT NULL,
	`discountPercent` decimal(5,2) DEFAULT '0',
	`discountAmount` decimal(12,2) DEFAULT '0',
	`totalAmount` decimal(12,2) NOT NULL,
	`amountDue` decimal(12,2) NOT NULL,
	`paymentTerms` varchar(255) DEFAULT 'Due upon receipt',
	`paymentReference` varchar(128),
	`bankName` varchar(128),
	`accountHolder` varchar(128),
	`accountNumber` varchar(64),
	`accountType` varchar(64),
	`branchCode` varchar(32),
	`notes` text,
	`invoiceDate` timestamp NOT NULL,
	`dueDate` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `invoices_id` PRIMARY KEY(`id`),
	CONSTRAINT `invoices_invoiceNumber_unique` UNIQUE(`invoiceNumber`)
);
